### PR TITLE
Added Twilio resources.

### PR DESCRIPTION
**Pull request by azeljkovic**

### CODE REVIEW

**Review by abhivaikar — APPROVED** [review]
Thanks for the contribution! 😊

**Comment by azeljkovic** [comment]
You’re welcome! :)

**Comment by azeljkovic** [comment]
Hi Abhijeet, I'm not able to merge this PR, shall you merge it?

**Comment by abhivaikar** [comment]
Hi @azeljkovic . Sorry for the late reply. I am merging your PR. Thanks! :)

**Pull request merged**
